repos:
  - repo: local
    hooks:
      - id: uv-isort
        name: isort (uv)
        entry: uv run --frozen isort
        language: system
        types: [python]
        require_serial: true
      - id: uv-black
        name: black (uv)
        entry: uv run --frozen black
        language: system
        types: [python]
        require_serial: true
